name: ds
description: DS

executables: 
  ds: 

environment:
  sdk: ^3.6.0

dependencies:
  args: ^2.7.0
  code_builder: ^4.10.1
  dart_style: ^2.3.7
  json_annotation: ^4.9.0
  path: ^1.9.1

dev_dependencies:
  build_runner: ^2.5.3
  json_serializable: ^6.9.5

