name: ds
description: DS

executables: 
  ds: 

environment:
  sdk: ^3.6.0

dependencies:
  args: ^2.7.0
  code_builder: ^4.10.1
  dart_style: ^2.3.7
  file: ^7.0.1
  json_annotation: ^4.9.0
  path: ^1.9.1
  shelf_proxy: ^1.0.4
  shelf_router: ^1.1.4
  shelf_web_socket: ^3.0.0
  toml: ^0.16.0
  watcher: ^1.1.2

dev_dependencies:
  build_runner: ^2.5.3
  json_serializable: ^6.9.5
  test: ^1.26.2

