name: ds
description: DS

executables: 
  ds: 

environment:
  sdk: ^3.7.0
dependencies:
  args: ^2.7.0
  code_builder: ^4.10.1
  dart_style: ^3.0.1
  json_annotation: ^4.9.0
  shelf: ^1.4.2
dev_dependencies:
  json_serializable: ^6.9.5
  build_runner: ^2.4.15

